#!/usr/bin/env python3
"""Upload a marker-pdf output Markdown file and its source PDF to Kronos as a knowledge base."""

import argparse
import json
import os
import sys
from pathlib import Path

import requests

DEFAULT_KRONOS_URL = "https://kronos-dev.alquist.ai"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="upload_to_kronos",
        description="Upload a marker-pdf output Markdown file and its source PDF to the Kronos "
                    "/knowledge_base/file/marker endpoint, creating a knowledge base in the given project.",
    )
    parser.add_argument("md", type=Path, help="Path to the paginated Markdown file generated by pdf2md.py.")
    parser.add_argument("pdf", type=Path, help="Path to the source PDF file.")
    parser.add_argument(
        "-p", "--project-id",
        required=True,
        help="ID of the Kronos project to create the knowledge base in.",
    )
    parser.add_argument(
        "-u", "--url",
        default=DEFAULT_KRONOS_URL,
        help=f"Base URL of the Kronos API (default: {DEFAULT_KRONOS_URL}).",
    )
    parser.add_argument(
        "-k", "--api-key",
        default=os.environ.get("KRONOS_API_KEY"),
        help="Kronos API key (default: taken from the KRONOS_API_KEY environment variable).",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    if not args.api_key:
        print("error: no API key given (use --api-key or set KRONOS_API_KEY)", file=sys.stderr)
        return 1

    for path in (args.md, args.pdf):
        if not path.is_file():
            print(f"error: file not found: {path}", file=sys.stderr)
            return 1

    files = [
        (
            "files",
            (
                path.name,
                path.open("rb"),
                "application/octet-stream",
            ),
        ) for path in (args.md, args.pdf)
    ]

    res = requests.post(
        url=f"{args.url.rstrip('/')}/knowledge_base/file/marker",
        headers={"X-Api-Key": args.api_key},
        params={"project_id": args.project_id},
        files=files,
    )

    try:
        print(json.dumps(res.json(), indent=2))
    except ValueError:
        print(res.text)

    return 0 if res.ok else 1


if __name__ == "__main__":
    sys.exit(main())
